// Crest Ocean System

// This file is subject to the MIT License as seen in the root of this folder structure (LICENSE)

// An implementation of the Jump Flood algorithm by Rong and Tan
// Source: https://www.comp.nus.edu.sg/~tants/jfa.html

#pragma kernel SdfInitJumpFlood

Texture2D<float4>   _FromTexture;
RWTexture2D<float2> _ToTexture;


[numthreads(8,8,1)]
void SdfInitJumpFlood(uint3 id : SV_DispatchThreadID)
{
	float4 result = _FromTexture[id.xy];
	_ToTexture[id.xy] = result.zw;
}
